# Generated by Django 4.2.26 on 2025-11-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setentry',
            name='rpe',
        ),
    ]
