# Generated by Django 4.2.26 on 2025-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_setentry_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='setentry',
            name='rpe',
            field=models.IntegerField(blank=True, help_text='Rate of Perceived Exertion (1-10)', null=True),
        ),
    ]
